# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:            Mohamed Imran
tagline:          'Software Engineering, Java, Cloud, Machine Learning'
url:              https://mohamedi.github.io/
shorturl:         mohamedi.github.io/

author:
  name:           'Mohamed Imran'
  url:            https://de.linkedin.com/in/mohamedimrannoormohamed

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           github.com/mohamedi/mohamedi.github.io

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
